apiVersion: v1
kind: Service
metadata:
  name: {{ include "qa-agent.fullname" . }}-api
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "qa-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.agentApi.service.type }}
  ports:
    - port: {{ .Values.agentApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.agentApi.service.type "NodePort") .Values.agentApi.service.nodePort }}
      nodePort: {{ .Values.agentApi.service.nodePort }}
      {{- end }}
  selector:
    {{- include "qa-agent.api.selectorLabels" . | nindent 4 }}
